---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30008