# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.hostname = "uteenaS"
  config.vm.box = "generic/alpine318"
  config.ssh.insert_key = false

  config.vm.network "private_network", ip: "192.168.56.11", auto_config: true, adapter: 2
  config.vm.synced_folder ".", "/shared"
  config.vm.provision :shell, path: "bootstrap.sh"
  
  config.vm.network "forwarded_port", guest: 80, host: 80

end
