# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.synced_folder ".", "/shared"
  config.vm.provision :shell, path: "bootstrap.sh"
end
