# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "uteenaS" do |server|
    server.vm.hostname = "uteenaS"
    server.vm.box = "generic/alpine318"
    server.ssh.insert_key = false

    server.vm.network "private_network", ip: "192.168.56.10", auto_config: true, adapter: 2
    server.vm.synced_folder ".", "/shared", type: "rsync", rsync__auto: true, rsync__exclude: ['Vagrantfile', './.vagrant']
    server.vm.provision :shell, path: "scripts/bootstrap.sh"

    server.vm.network "forwarded_port", guest: 80, host: 80

  end

end