# -*- mode: ruby -*-
# vi: set ft=ruby :

# This is only for fast VM setup (will be deleted later)

Vagrant.configure("2") do |config|

  config.vm.define "testVM" do |server|
    server.vm.hostname = "testVM"
    server.vm.box = "ubuntu/focal64"
    server.vm.synced_folder ".", "/shared", type: "rsync", rsync__auto: true,  rsync__exclude: ['Vagrantfile', './.vagrant']
    server.ssh.insert_key = false

    server.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"
    server.vm.network "forwarded_port", guest: 8888, host: 8888, protocol: "tcp"

  end

end
