# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/shared"

  config.vm.define "uteenaS" do |server|

    server.vm.box = "generic/alpine318"
    server.vm.hostname = "uteenaS"
    server.vm.network "private_network", ip: "192.168.56.110", auto_config: true, adapter: 2
    server.vm.provision "shell", inline: <<-SHELL
      sudo apk update
      sudo apk add curl
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" sh - 
      while [ ! -f /var/lib/rancher/k3s/server/token ]; do
        sleep 1
      done
      sudo cp /var/lib/rancher/k3s/server/token /shared/token
    SHELL

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

  end

  config.vm.define "uteenaSW" do |worker|

    worker.vm.box = "generic/alpine318"
    worker.vm.hostname = "uteenaSW"
    worker.vm.network "private_network", ip: "192.168.56.111", auto_config: true, adapter: 2

    worker.vm.provision "shell", inline: <<-SHELL
      sudo apk update
      sudo apk add curl

     while [ ! -f /shared/token ]; do
        sleep 1
      done
      CONTROLLER_IP="192.168.56.110"
      TOKEN=$(sudo cat /shared/token)
      INSTALL_K3S_EXEC="--flannel-iface eth1"

      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_URL=https://${CONTROLLER_IP}:6443 K3S_TOKEN=${TOKEN} sh -
    SHELL

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end

  end

end
