# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "uteenaS" do |server|

    server.vm.box = "generic/alpine318"
    server.vm.hostname = "uteenaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
      sudo apk update
      sudo apk add curl
      curl -sfL https://get.k3s.io | sh -
    SHELL

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

  end

  config.vm.define "uteenaSW" do |worker|

    worker.vm.box = "generic/alpine318"
    worker.vm.hostname = "uteenaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    # worker.vm.provision "shell", inline: <<-SHELL
    #   sudo apk update
    #   sudo apk add curl
    #
    #   CONTROLLER_IP="192.168.56.110"
    #   TOKEN=$(ssh -o StrictHostKeyChecking=no -i /vagrant/id_rsa vagrant@${CONTROLLER_IP} sudo cat /var/lib/rancher/k3s/server/node-token)
    #
    #   curl -sfL https://get.k3s.io | K3S_URL=https://${CONTROLLER_IP}:6443 K3S_TOKEN=${TOKEN} sh -
    #   sudo apk add kubectl
    # SHELL

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end

  end

  config.ssh.insert_key = false

end
